<?php

/**
 * Implements hook_views_post_execute().
 */

GLOBAL $dataArray;

function searchtap_help_views_post_execute(&$view) {

    if($view->name=='jsonproduct') {
     foreach ($view->result as $key => &$result) {

    $images = array();
    $images = explode(',',$view->render_field('uc_product_image',$key));
    foreach ($images as $img) {
        $doc = new DOMDocument();
        $p_result_without_null_chars = str_replace("\0", '', $img);
        $doc->loadHTML($p_result_without_null_chars);
        $xpath = new DOMXPath($doc);
        $src= $xpath->evaluate("string(//img/@data-src)");
        $result->views_php_28=$src;

    }
         // for multiple image
         //
         //
         //$img_urls = array();
         //foreach ($node->field_image as $item) {
         //  if ($item->entity) {
         //    $img_urls[] = $item->entity->url();
         //  }
         //}

   $relationship=array();
   $relationship=explode(',',$view->render_field('field_relationship',$key));
  // var_dump($relationship);
    foreach ($relationship as $rel) {
        $doc = new DOMDocument();
        $p_result_without_null_chars = str_replace("\0", '', $rel);
        $doc->loadHTML($p_result_without_null_chars);
        $xpath = new DOMXPath($doc);
        $src = $xpath->evaluate("string(//a/@title)");
        $result->views_php_29=$src;
    }


   $caketype=array();
   $caketype=explode(',',$view->render_field('field_cake_type',$key));

   foreach ($caketype as $cake) {
        $doc = new DOMDocument();
        $p_result_without_null_chars = str_replace("\0", '', $cake);
        $doc->loadHTML($p_result_without_null_chars);
        $xpath = new DOMXPath($doc);
        $src = $xpath->evaluate("string(//a/@title)");
        $result->views_php_31=$src;
    }

  $title=array();
   $title=explode(',',$view->render_field('title',$key));

   foreach ($title as $t) {
        $doc = new DOMDocument();
        $p_result_without_null_chars = str_replace("\0", '', $t);
        $doc->loadHTML($p_result_without_null_chars);
        $xpath = new DOMXPath($doc);
        $src = $xpath->evaluate("string(//a/@title)");
        $result->views_php_34=$src;
    }


   $planttype=array();
   $planttype=explode(',',$view->render_field('field_plant_type',$key));

 foreach ($planttype as $plant) {
        $doc = new DOMDocument();
        $p_result_without_null_chars = str_replace("\0", '', $plant);
        $doc->loadHTML($p_result_without_null_chars);
        $xpath = new DOMXPath($doc);
        $src = $xpath->evaluate("string(//a/@title)");
        $result->views_php_32=$src;
    }

 //var_dump($view->result);


  $occasiondata=array();
  $occasiondata=explode(',',$view->render_field('field_occasion_new',$key));
  foreach ($occasiondata as $occasion) {

            $src= array_unique($occasiondata);
            $result->views_php_35=array_map('trim',$src);


  }
  //var_dump($result->views_php_35);

    $Availablecity=array();
    $Availablecity=explode(',',$view->render_field('field_available_cities',$key));
    foreach ($Availablecity as $availcity) {

             $src =array_unique($Availablecity);
             $result->views_php_38=array_map('trim',$src);
    }

    $bouquet=array();
    $bouquet=explode(',',$view->render_field('field_bouquet',$key));
    foreach ($bouquet as $bq) {

        $src =array_unique($bq);
        $result->views_php_37=array_map('trim',$src);
    }


    $gift_type=array();
    $gift_type=explode(',',$view->render_field('field_gift_type',$key));
    foreach ($gift_type as $gift) {

        $src =array_unique($gift);
        $result->views_php_33=array_map('trim',$src);
    }
         $tag_type=array();
         $tag_type=explode(',',$view->render_field('field_tag',$key));
         foreach ($tag_type as $tag) {

             $doc = new DOMDocument();
             $p_result_without_null_chars = str_replace("\0", '', $tag);
             $doc->loadHTML($p_result_without_null_chars);
             $xpath = new DOMXPath($doc);
             $src = $xpath->evaluate("string(//a/@title)");
             $result->views_php_30=$src;
         }

     }
    }
}
